#!/bin/bash

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}')
echo $volume

# Edit what you grep for, unless you're running Swedish
function pavol() { pactl subscribe | grep "'ändra' på mottagare"; }
export -f pavol


(stdbuf -oL bash -c 'pavol') |
while read
do

volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{ print $5}')
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | cut -d" " -f2)

# Change "ja" to "yes" if you're running English, I guess?
if [ "$mute" = "ja" ]; then
        echo "  M   "
elif [ "${#volume}" -lt 3 ]; then
	echo 0$volume
else
	echo $volume
fi
done
